wandb_version: 1

random seed:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 2
note:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709388710.80648
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: Batch step
    - 1: Train/Classification Loss(GCE)
      5: 1
      6:
      - 1
    - 1: Epoch step
    - 1: Accuracy/Trainset
      5: 3
      6:
      - 1
    - 1: Accuracy/Validset
      5: 3
      6:
      - 1
    - 1: Valid/Validset Classification Loss(GCE)
      5: 3
      6:
      - 1
    - 1: Accuracy/Testset
      5: 3
      6:
      - 1
    - 1: Valid/Testset Classification Loss(GCE)
      5: 3
      6:
      - 1
