wandb_version: 1

random seed:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 100
note:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709383336.437597
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
